name: pkg-test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  pkg-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
          use-public-rspm: true

      - name: Install LaTeX for PDF manual
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            lmodern \
            pandoc

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            sf
            terra
            digest
            rmarkdown
            knitr
            tinytex

      - name: Run R CMD check
        run: R CMD check --as-cran .